"""empty message

Revision ID: 317281e7ee47
Revises: 62327a62b39e
Create Date: 2021-04-02 23:45:31.865156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317281e7ee47'
down_revision = '62327a62b39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('classification', sa.String(length=250), nullable=False),
    sa.Column('designation', sa.String(length=250), nullable=True),
    sa.Column('average_height', sa.Integer(), nullable=True),
    sa.Column('average_lifespan', sa.Integer(), nullable=True),
    sa.Column('hair_colors', sa.String(length=250), nullable=True),
    sa.Column('skin_colors', sa.String(length=250), nullable=True),
    sa.Column('eye_colors', sa.String(length=250), nullable=True),
    sa.Column('language', sa.String(length=250), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specie')
    # ### end Alembic commands ###
