"""empty message

Revision ID: 62327a62b39e
Revises: 4ae3d7a1c1e8
Create Date: 2021-04-01 02:03:58.059151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62327a62b39e'
down_revision = '4ae3d7a1c1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('favorite_name', sa.String(length=250), nullable=False),
    sa.Column('favorite_type', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
