"""empty message

Revision ID: 788c31667ae1
Revises: a16ce43536fd
Create Date: 2021-04-03 02:23:26.483231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '788c31667ae1'
down_revision = 'a16ce43536fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('title', sa.String(length=250), nullable=False))
    op.drop_column('film', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('film', 'title')
    # ### end Alembic commands ###
