"""empty message

Revision ID: a16ce43536fd
Revises: f1792dc10e0c
Create Date: 2021-04-03 00:10:20.893584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16ce43536fd'
down_revision = 'f1792dc10e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('producer', sa.String(length=250), nullable=False),
    sa.Column('director', sa.String(length=250), nullable=False),
    sa.Column('release_date', sa.String(length=250), nullable=False),
    sa.Column('opening', sa.String(length=8000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_planets',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('planet_id', 'film_id')
    )
    op.create_table('film_characters',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'film_id')
    )
    op.create_table('film_species',
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['specie.id'], ),
    sa.PrimaryKeyConstraint('specie_id', 'film_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_species')
    op.drop_table('film_characters')
    op.drop_table('film_planets')
    op.drop_table('film')
    # ### end Alembic commands ###
